trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage : Build
  jobs:
   - job: FirstJob
     steps:
     - bash : echo Build stage first job
     - bash : echo $(Build.BuildNumber)
     - bash : echo $(Build.BuildId)
     - bash : echo $(Build.SourceBranchName)
     - bash : echo $(Build.SourcesDirectory)
     - bash : echo $(System.DefaultWorkingDirectory)
     - bash : ls -R $(System.DefaultWorkingDirectory)
     - bash : echo $(Build.ArtifactStagingDirectory)
     - bash : java -version
     - bash : python --version
     - bash : node --version
     - bash : mvn -version
     - bash : ls -R $(Build.ArtifactStagingDirectory)
     
     - task: CopyFiles@2
       inputs:
         SourceFolder: '$(System.DefaultWorkingDirectory)'
         Contents: |
           **/*.yaml
           **/*.tf
         TargetFolder: '$(Build.ArtifactStagingDirectory)'
     - bash : ls -R $(Build.ArtifactStagingDirectory)

     - task: PublishBuildArtifacts@1
       inputs:
         PathtoPublish: '$(Build.ArtifactStagingDirectory)'
         ArtifactName: 'drop'
         publishLocation: 'Container'
         
  #  - job: SecondJob
  #    steps:
  #    - bash : echo Build stage Second job

# - stage : DevDeploy
#   variables :
#     environment : Dev
#   dependsOn : Build
#   jobs:
#    - job: DevDeployJob
#      steps:
#      - bash : echo $(environment)Deploy Variable

# - stage : QADelpoy
#   variables :
#     environment : QA
#   dependsOn : Build
#   jobs:
#    - job: QADelpoyJob
#      steps:
#      - bash : echo $(environment)Delpoy Variable
     
# - stage : ProdDeploy
#   variables :
#     environment : Prod
#   dependsOn : 
#   - DevDeploy
#   - QADelpoy
#   jobs:
#    - job: ProdDeployJob
#      steps:
#      - bash : echo $(environment)Deploy Variable