trigger:
- main

# strategy:
#   matrix:
#     linux:
#       OperatingSystem: 'ubuntu-latest'
#     mac:
#       OperatingSystem: 'macos-latest'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage:
  jobs:
  - job:
    steps:
    - bash: echo "Do the build"

- stage: DevDeploy
  jobs:
  - deployment: DevDeployJob
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo Deploy to Dev

- stage: QADeploy
  jobs:
  - deployment: QADeployJob
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo Deploy to QA




