trigger:
- main

strategy:
  matrix:
    linux:
      OperatingSystem: 'ubuntu-latest'
    mac:
      OperatingSystem: 'macos-latest'

pool:
  vmImage: $(OperatingSystem)

steps:
- script: echo rinning on $(OperatingSystem)!
  displayName: 'Run a one-line script'
