trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo K8s Azure Terraform !
  displayName: 'Run a one-line script'

# - task: TerraformInstaller@1
#   displayName: 'Install Terraform CLI'
#   inputs:
#     terraformVersion: 'latest'

- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure-rsa'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    # commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendAzureRmUseEntraIdForAuthentication: false
    backendServiceArm: 'azure-resource-manager'
    backendAzureRmResourceGroupName: 'kubernetes-rg'
    backendAzureRmStorageAccountName: 'kubernetestoragevishal'
    backendAzureRmContainerName: 'storageaccountcontainer'
    backendAzureRmKey: 'kubernetes-dev.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    environmentServiceNameAzureRM: 'azure-resource-manager'
