trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage : Build
  jobs:
   - job: FirstJob
     steps:
     - bash : echo Build stage first job
   - job: SecondJob
     steps:
     - bash : echo Build stage Second job

- stage : DevDeploy
  jobs:
   - job: DevDeployJob
     steps:
     - bash : echo DevDeploy
- stage : QADelpoy
  jobs:
   - job: QADelpoyJob
     steps:
     - bash : echo QADelpoy
- stage : ProdDeploy
  jobs:
   - job: ProdDeployJob
     steps:
     - bash : echo ProdDeploy
