trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage : Build
  jobs:
   - job: FirstJob
     steps:
     - bash : echo Build stage first job
   - job: SecondJob
     steps:
     - bash : echo Build stage Second job

- stage : DevDeploy
  dependsOn : Build
  jobs:
   - job: DevDeployJob
     steps:
     - bash : echo DevDeploy

- stage : QADelpoy
  dependsOn : Build
  jobs:
   - job: QADelpoyJob
     steps:
     - bash : echo QADelpoy
     
- stage : ProdDeploy
  dependsOn : 
  - DevDeploy
  - QADelpoy
  jobs:
   - job: ProdDeployJob
     steps:
     - bash : echo ProdDeploy
